"""Add before_cutoff field to Purchase model

Revision ID: 654ed1962940
Revises: 
Create Date: 2025-03-22 10:35:46.699331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654ed1962940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_cutoff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('before_cutoff')

    # ### end Alembic commands ###
